In [1]:
# 1.1.	Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5
# 2.1.	Из полученного массива получить массив с кратными 10 числами
# 3.1.	Получить двумерный массив с двумя столбцами
# 4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5
# 5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.
# 6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы
# 7.1.	Оставить только те значения, которые не изменились после деления
# 8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки
# 9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().
# 10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.


<h1>Numpy</h1>

In [2]:
import numpy as np

1.1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [3]:
my_array=np.arange(5,101,5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

2.1.	Из полученного массива получить массив с кратными 10 числами

In [4]:
result_array = my_array[my_array % 10 == 0]
result_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

3.1.	Получить двумерный массив с двумя столбцами

In [5]:
two_array=np.column_stack((result_array, result_array))
two_array

array([[ 10,  10],
       [ 20,  20],
       [ 30,  30],
       [ 40,  40],
       [ 50,  50],
       [ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [6]:
my_second_array= two_array-5
my_second_array

array([[ 5,  5],
       [15, 15],
       [25, 25],
       [35, 35],
       [45, 45],
       [55, 55],
       [65, 65],
       [75, 75],
       [85, 85],
       [95, 95]])

5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [7]:
combined_array = np.hstack((two_array[:, np.newaxis], my_second_array[:, np.newaxis])).T
combined_array

array([[[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]],

       [[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]]])

6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [8]:
selected_rows = my_array[1:3]
top_rows = my_array[:4]
result_matrix = selected_rows[:, np.newaxis] / top_rows
result_matrix

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [3.        , 1.5       , 1.        , 0.75      ]])

7.1.	Оставить только те значения, которые не изменились после деления

In [9]:
filtered_values = result_matrix[result_matrix == result_matrix.astype(int)]
filtered_values

array([2., 1., 3., 1.])

8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [10]:
three_row_matrix = my_array.reshape(3, -1)
three_row_matrix[0], three_row_matrix[2] = three_row_matrix[2].copy(), three_row_matrix[0].copy()
print(three_row_matrix)

ValueError: cannot reshape array of size 20 into shape (3,newaxis)

In [ ]:
list = np.array([[1,2,3],[4,5,6], [7,8,9]])
print ('Матрица до изменений\n',list)
list[0],list[2] = list[2], list[0]
print ('Матрица после\n',list)

9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [ ]:
list1 = np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12]])
for i in list1:
    mean = np.mean(i)
    median = np.median(i)
    std = np.std(i)
    print ('Stroka', i, '\nmean: ', mean, 'median', median, 'std:', std)

10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк

In [ ]:
list2 = np.arange(1,13).astype(float).reshape(3,4)
for i in range(len(list2)):
    maxValue = np.max(list2[i])
    list2[i] = list2[i] / maxValue
print(list2)

<h1>Pandas</h1>

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("Global Population Trends(2016-2022).csv")
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

2.2.	 Считайте несколько первых записей таблицы (head())

In [14]:
header=df.head(10)
header

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
5      Albania  2017                -                -                -   
6      Albania  2018        2,866,376        1,728,969        1,137,407   
7      Albania  2019        2,854,191        1,747,593        1,106,598   
8      Albania  2020        2,837,849        1,762,645        1,075,204   
9      Albania  2021        2,811,666        1,770,478        1,041,188   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   
5                105            79.0      10.870       8.150          1.491   
6                105            79.0      10.517       8.308           1.44   
7                104            79.0      10.343       8.480          1.414   
8                104            77.0      10.285      10.785            1.4   
9                  -            76.0      10.240      11.325           1.39   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0  
5                   8.3           -  
6                   8.3         0.0  
7                   8.4         0.0  
8                   8.4        -1.0  
9                   8.4        -1.0

2.3.	 Определите размерность данного фрейма (shape())

In [15]:
df.shape

(1073, 12)

2.4.	 Выведите название заголовков столбцов фрейма (columns)

In [16]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

2.5.	Получите описание всех переменных (полей) (info())

In [17]:
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-”

In [18]:
drop=df.drop(df[df['Total Population'] == '-'].index, inplace=True)
df

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())

In [20]:
max_population = df['Life Expectancy'].max()
max_population

ValueError: invalid literal for int() with base 10: '63.0'

In [ ]:
min_population=df['Life Expectancy'].min()
min_population

In [ ]:
describe_info=df['Country'].describe()
describe_info

2.8.	Выполните сортировку данных по нескольким критериям

In [27]:
sorted_df = df.sort_values(by=['Country', 'Year'], ascending=[False, True])
sorted_df


Country  Year  Total Population Urban Population Rural Population  \
1069     Zimbabwe  2018          15052184        4,848,158       10,204,026   
1070     Zimbabwe  2019          15354608        4,945,719       10,408,889   
1071     Zimbabwe  2020          15669666        5,052,214       10,617,452   
1072     Zimbabwe  2021          15993524        5,166,388       10,827,136   
1064       Zambia  2018          17835893        7,762,359       10,073,534   
...           ...   ...               ...              ...              ...   
9         Albania  2021           2811666        1,770,478        1,041,188   
1     Afghanistan  2018          36686784        9,353,296       27,333,488   
2     Afghanistan  2019          37769499        9,727,157       28,042,342   
3     Afghanistan  2020          38972230       10,142,913       28,829,317   
4     Afghanistan  2021          40099462       10,551,772       29,547,690   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   
1064                 24            62.0      36.040       6.748   
...                 ...             ...         ...         ...   
9                     -            76.0      10.240      11.325   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   

     Fertility Rate Infant Mortality Rate Growth Rate  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  
1064          4.536                  43.6         3.0  
...             ...                   ...         ...  
9              1.39                   8.4        -1.0  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  

[864 rows x 12 columns]

2.9. Выведите название страны, которая имеет максимальную численность населения

In [37]:
df1=pd.DataFrame(df)
index_max_population=df1["Total Population"].idxmax()
country_with_max_population=df1.loc[index_max_population, "Country"]
country_with_max_population

'China'

2.10.	Выведите название страны, которая имеет минимальную численность населения

In [38]:
df1=pd.DataFrame(df)
index_min_population=df1["Total Population"].idxmin()
country_with_min_population=df1.loc[index_min_population, "Country"]
country_with_min_population

'Tuvalu'

2.11.	Экспорт фрейма в MS Excel

In [ ]:
df1 = pd.DataFrame(df)
df1.to_excel("Global Population Trends(2016-2022).xlsx", index=False)